service: coffee-shop-api
frameworkVersion: '3.40.0'

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: us-east-2

  environment:
    STAGE: ${opt:stage, 'dev'}
    TABLE_NAME: ${self:service}-${opt:stage, 'dev'}-orders

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:Scan
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: arn:aws:dynamodb:us-east-2:*:table/${self:service}-${opt:stage, 'dev'}-orders

functions:
  # Modular function imports
  ${file(./functions/createOrder.yml)}
  ${file(./functions/getOrder.yml)}
  ${file(./functions/listOrders.yml)}
  ${file(./functions/updateOrder.yml)}
  ${file(./functions/deleteOrder.yml)}

package:
  individually: true  # Package functions separately for faster deployment and cleaner bundles

resources:
  ${file(./resources/dynamodb.yml)}  # Modular resource definition